#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

$configurationFile = getGitDir() . DIRECTORY_SEPARATOR . '.pre-commit.yml';

$app = new \PhpHooks\Application();
$app->setFiles(extractFiles());

if (file_exists($configurationFile)) {
    $app->updateConfiguration($configurationFile);
}

$app->run();

function extractFiles()
{
    if (false === function_exists('exec')) {
        throw new \RuntimeException('Function exec must be enabled!');
    }

    $gitDir = getGitDir();

    $output = array();
    exec("git diff --cached --name-status --diff-filter=ACMR", $output);

    $files = array_map(function ($v) use ($gitDir) {
        $file = trim(str_replace(array('M', 'C', 'A', 'R'), '', $v));
        return $gitDir . DIRECTORY_SEPARATOR . $file;
    }, $output);

    return $files;
}

function getGitDir()
{
    if (false === function_exists('exec')) {
        throw new \RuntimeException('Function exec must be enabled!');
    }

    $path = array();
    exec("git rev-parse --show-toplevel", $path);

    return current($path);
}